version: '3.8'

services:
  yew-ui:
    volumes:
      - type: bind
        source: ../
        target: /app
    build: 
      dockerfile: ../docker/Dockerfile.yew
    command: bash -c "cd app/yew-ui && trunk serve --address 0.0.0.0"
    environment:
      - ACTIX_PORT=8086 
      - TRUNK_SERVE_PORT=80
      - ENABLE_OAUTH=false
      - OAUTH_CLIENT_ID=""
      - OAUTH_AUTH_URL=""
      - OAUTH_TOKEN_URL=""
      - OAUTH_CLIENT_SECRET=""
    ports:
      - "80:80"  
  actix-api:
    build: 
      dockerfile: ../docker/Dockerfile.actix
    command: bash -c "cd app/actix-api && cargo watch -x \"run\""
    environment:
      - ACTIX_PORT=8086
      - TRUNK_SERVE_PORT=80
      - TRUNK_SERVE_HOST=localhost
    ports:
      - "8086:8086"
    volumes:
      - type: bind
        source: ../
        target: /app