name: Security audit
on: [pull_request]
# on:
#   push:
#     paths: 
#       - '**/Cargo.toml'
#       - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: security-union/audit-check@3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  