name: Security audit
on: [pull_request]
# on:
#   push:
#     paths: 
#       - '**/Cargo.toml'
#       - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./actix-web
  